"""Versioned normative catalogs for odontogram profiles.

Read-only data plus the schema and validator that keep it honest. Nothing
here persists clinical information: a catalog says what a norm *requires*,
not what was found in a patient's mouth.
"""

from app.modules.odontogram.nts.catalog.loader import (
    CatalogNotFoundError,
    available_norm_versions,
    get_nts_catalog,
    get_nts_rule,
)
from app.modules.odontogram.nts.catalog.schema import (
    MARK_PARAMS,
    REQUIRED_MARK_PARAMS,
    ArrowDirection,
    ArrowStyle,
    AttributeDef,
    AttributeKind,
    ColorSemantics,
    ConnectorStyle,
    FillStyle,
    GeometryInput,
    GeometryMode,
    GlobalRule,
    LineMeaning,
    LineStyle,
    MarkPlacement,
    NtsCatalog,
    NtsRule,
    OutlineStyle,
    RenderKind,
    RenderMark,
    ReviewStatus,
    RoleAppliesTo,
    RoleDef,
    Scope,
    SiglaCase,
    SpecificationRequirement,
    SymbolShape,
    TargetSelector,
    VariantValue,
)
from app.modules.odontogram.nts.catalog.validator import (
    CatalogValidationError,
    validate_nts_catalog,
)

__all__ = [
    "MARK_PARAMS",
    "REQUIRED_MARK_PARAMS",
    "ArrowDirection",
    "ArrowStyle",
    "AttributeDef",
    "AttributeKind",
    "CatalogNotFoundError",
    "CatalogValidationError",
    "ColorSemantics",
    "ConnectorStyle",
    "FillStyle",
    "GeometryInput",
    "GeometryMode",
    "GlobalRule",
    "LineMeaning",
    "LineStyle",
    "MarkPlacement",
    "NtsCatalog",
    "NtsRule",
    "OutlineStyle",
    "RenderKind",
    "RenderMark",
    "ReviewStatus",
    "RoleAppliesTo",
    "RoleDef",
    "Scope",
    "SiglaCase",
    "SpecificationRequirement",
    "SymbolShape",
    "TargetSelector",
    "VariantValue",
    "available_norm_versions",
    "get_nts_catalog",
    "get_nts_rule",
    "validate_nts_catalog",
]
